#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            terraform init
            terraform apply -auto-approve
  deploy:
    docker:
      - image: opspresso/awscli
    steps:
      - checkout
      - run:
          name: AWS S3 Sync
          command: |
            aws s3 sync src/www/ s3://www.opspresso.com/ --acl public-read
            aws s3 sync src/repo/ s3://repo.opspresso.com/ --acl public-read

workflows:
  version: 2
  lambda:
    jobs:
      - build
      - deploy:
          requires:
            - build
